// <auto-generated />
using CrossPlatformPasswordManager.Core.Context;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CrossPlatformPasswordManager.Core;

#nullable disable

namespace CrossPlatformPasswordManager.Core.Migrations
{
    [DbContext(typeof(PasswordManagerContext))]
    [Migration("20251011003933_CreateMasterPasswordTable")]
    partial class CreateMasterPasswordTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PasswordManager.Data.Models.MasterPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyDerivationSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
